### ISSUE TITLE
Optimization for batch traversal

### ISSUE THREAD

**Issue by leeopop** [ANLAB-KAIST/NBA#24]
In 591fe18, Joongi has implemented swap-based continuous batches to eliminate branching overheads in per-packet iterations.
As a packet processing framework, it would be nice if we could avoid packet reordering even inside batches.
I think ffs (find-first significant bit), ffz (find-first zero bit) intrinsics may be a great solution for this.

* [x] Rewrite all iteration loops to use a common iterator definition (using macro or functions).
* [x] Ensure that the current scheme work with new iteration loop definition.
* [x] Implement ffs/ffz-based iteration loop and remove `collect_excluded_packets()` in PacketBatch.

**Comment by achimnol** [comment]
Done with #5 issue and a feature branch.
Now time to run branching workload tests.
